### Get all franchises
GET http://localhost:8080/api/franchises
Accept: application/json

### Get franchise
@get_franchise_id =
GET http://localhost:8080/api/franchises/{{get_franchise_id}}
Accept: application/json

### Get all players
GET http://localhost:8080/api/players
Accept: application/json

### Get player
@get_player_id =
GET http://localhost:8080/api/players/{{get_player_id}}
Accept: application/json

### Create franchise
POST http://localhost:8080/api/franchises
Content-Type: application/json

{
  "name": "Los Angeles Lakers",
  "city": "Los Angeles",
  "conference": "West",
  "titles": 17,
  "currentPosition": 3
}

### Add player to franchise
@add_id =
POST http://localhost:8080/api/franchises/{{add_id}}/players
Content-Type: application/json

{
  "firstName": "Lebron",
  "lastName": "James",
  "age": 38,
  "position": "FORWARD"
}


### Update franchise
@update_franchise_id =
PUT http://localhost:8080/api/franchises/{{update_franchise_id}}
Content-Type: application/json

{
  "name": "Los Angeles Lakers",
  "city": "Los Angeles",
  "conference": "West",
  "titles": 18,
  "currentPosition": 2
}

### Update player
@update_player_id =
PUT http://localhost:8080/api/players/{{update_player_id}}
Content-Type: application/json

{
  "firstName": "Lebron",
  "lastName": "James",
  "age": 40,
  "position": "CENTER"
}

### Transfer player
@transfer_franchise_id =
@transfer_player_id =
PUT http://localhost:8080/api/players/{{transfer_player_id}}/franchise/{{transfer_franchise_id}}
Accept: application/json

### Delete player
@delete_player_id =
DELETE http://localhost:8080/api/players/{{delete_player_id}}
Accept: application/json

### Delete franchise
@delete_franchise_id =
DELETE http://localhost:8080/api/franchises/{{delete_franchise_id}}
Accept: application/json