### Get all franchises
GET http://localhost:8080/api/franchises
Accept: application/json

### Get all players from franchise
@franchise_id_1 = 7a3d4a52-ae53-4066-8fa0-9e98c7ab7479
GET http://localhost:8080/api/players/franchise/{{franchise_id_1}}/players
Accept: application/json

### Get franchise
@get_franchise_id = 50ca0902-82ac-408d-962a-4e0a20c9661d
GET http://localhost:8080/api/franchises/{{get_franchise_id}}
Accept: application/json

### Get all players
GET http://localhost:8080/api/players
Accept: application/json

### Get player
@get_player_id =9c9f4aef-e725-498b-9830-f0378baa4062
GET http://localhost:8080/api/players/{{get_player_id}}
Accept: application/json

### Create franchise
POST http://localhost:8080/api/franchises
Content-Type: application/json

{
  "name": "Los Angeles Lakers",
  "city": "Los Angeles",
  "conference": "West",
  "titles": 17,
  "currentPosition": 3
}

### Add franchise to player
@add_id =c2b3e817-da3f-4ce1-aff7-a7b31b9292f2
POST http://localhost:8080/api/players/{{add_id}}
Content-Type: application/json

{
  "firstName": "Lebron",
  "lastName": "James",
  "age": 38,
  "position": "FORWARD"
}


### Update franchise
@update_franchise_id = d1e84fc9-e33b-442c-9796-b304e735d06b
PUT http://localhost:8080/api/franchises/{{update_franchise_id}}
Content-Type: application/json

{
  "name": "Los Angeles Lakers",
  "city": "Los Angeles",
  "conference": "West",
  "titles": 15,
  "currentPosition": 5
}

### Update player
@update_player_id =60a150a5-a52d-4020-84ea-6216e38a15fe
PUT http://localhost:8080/api/players/{{update_player_id}}
Content-Type: application/json

{
  "firstName": "Lebron",
  "lastName": "James",
  "age": 40,
  "position": "CENTER"
}

### Transfer player
@transfer_franchise_id =c2b3e817-da3f-4ce1-aff7-a7b31b9292f2
@transfer_player_id =9fde382a-f497-4705-84f4-77826a0fa98f
PUT http://localhost:8080/api/players/{{transfer_player_id}}/franchise/{{transfer_franchise_id}}
Accept: application/json

### Delete player
@delete_player_id =92fdaada-50ba-4d91-8cd0-dabadb357afd
DELETE http://localhost:8080/api/players/{{delete_player_id}}
Accept: application/json

### Delete franchise
@delete_franchise_id = 7a3d4a52-ae53-4066-8fa0-9e98c7ab7479
DELETE http://localhost:8080/api/franchises/{{delete_franchise_id}}
Accept: application/json